# Generated by Django 4.2.4 on 2023-08-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('date_of_publish', models.DateField()),
                ('thubnail', models.ImageField(upload_to='blog/thumb')),
                ('body', models.TextField()),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywors', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('author', models.CharField(blank=True, default='', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=50)),
                ('thumb', models.ImageField(upload_to='courses/thumb')),
                ('slug', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('role', models.CharField(default='', max_length=50)),
                ('profile_picture', models.ImageField(upload_to='staf/profile_picture')),
            ],
        ),
    ]
