# Generated by Django 4.2.4 on 2023-08-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_blog_thubnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thubnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/thumb'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumb',
            field=models.ImageField(help_text='size=200*200', upload_to='courses/thumb'),
        ),
    ]
