# Generated by Django 4.2.4 on 2023-08-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_course_short_description_alter_blog_thubnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', help_text='link of page ex /blog/tutorial1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='link of page ex /blog/tutorial1'),
        ),
    ]
