# Generated by Django 4.2.4 on 2023-08-22 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_course_slug_alter_blog_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='thubnail',
            new_name='thumb',
        ),
    ]
