# Generated by Django 4.2.4 on 2023-08-23 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_thubnail_blog_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(help_text='link of page ex /tutorial1'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumb',
            field=models.ImageField(upload_to='courses/thumb'),
        ),
        migrations.CreateModel(
            name='tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(help_text='link of page ex /tutorial1')),
                ('date_of_publish', models.DateField()),
                ('body', models.TextField()),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywors', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.auther')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
            ],
        ),
    ]
