# Generated by Django 4.2.4 on 2023-08-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='tut_download_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('file', models.FileField(upload_to='tutorials/download-dat')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.tutorial')),
            ],
        ),
    ]
