# Generated by Django 4.2.4 on 2023-08-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_course_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course_unit',
        ),
    ]
