# Generated by Django 4.2.4 on 2023-08-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delete_course_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
