# Generated by Django 4.2.4 on 2023-08-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_blog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
