# Generated by Django 4.2.4 on 2023-08-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_blog_name_tutorial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='name',
        ),
    ]
