# Generated by Django 4.2.4 on 2023-08-25 14:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_blog_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
