# Generated by Django 4.2.4 on 2023-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_tutorial_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
