# Generated by Django 4.2.4 on 2023-08-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_blog_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank=True, help_text='640*426', null=True, upload_to='blog/thumb'),
        ),
    ]
