# Generated by Django 4.2.4 on 2023-08-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_blogcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tut_download_file',
            new_name='download_file',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(to='app1.blogcategory'),
        ),
    ]
