# Generated by Django 4.2.4 on 2023-08-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_rename_tut_download_file_download_file_blog_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='staf',
            new_name='Tutor',
        ),
        migrations.AddField(
            model_name='download_file',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='Tutor/profile_pic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='download_file',
            name='short_description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='download_file',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
