# Generated by Django 4.2.4 on 2023-08-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_rename_tutor_staf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='meta_keywors',
            new_name='meta_keywords',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='meta_keywors',
            new_name='meta_keywords',
        ),
    ]
